### ISSUE TITLE
May be you should put a disclaimer or some kind of warning.

### ISSUE THREAD

**Issue by vidyap-xgboost** [kurasaiteja/Whatsapp-Analysis#2]
I see that this is a boys group chat and a disclaimer or some kind of warning would be nice because of the words which can be considered as 'unparliamentary'. Pointing this out only because one can expect what kind of messages/words they would be seeing while going through your notebook.

Awesome work btw. 👍

**Comment by kurasaiteja** [comment]
Thanks for the suggestion. Will try doing something about the point you mentioned :)
